---
  - name: stop ambari agent services in all nodes
    ignore_errors: yes
    shell: "systemctl stop ambari-agent"
    tags:
      - stop_ambari_agent

  - name: display status of ambari agent services in all nodes
    ignore_errors: yes
    register: status
    shell: "systemctl status ambari-agent"
    tags:
      - status_ambari_agent

  - name: display ambari agent status
    debug: msg="{{ status }}"
    tags:
      - status_ambari_agent

  - name: remove ambari repo
    ignore_errors: yes
    register: ambari_repo_remove
    shell: "rm -rf /etc/yum.repos.d/ambari.repo"
    tags:
      - update_ambari_repo

  - name: add ambari repo
    ignore_errors: yes
    register: add_repo_remove
    template:
      src: "ambari.repo.j2"
      dest: "/etc/yum.repos.d/ambari.repo"
    tags:
      - update_ambari_repo

  - name: clean ambari repo
    ignore_errors: yes
    shell: "yum clean all"
    tags:
      - upgrade_ambari_agent

  - name: upgrade ambari agent
    ignore_errors: yes
    shell: "yum -y upgrade ambari-agent"
    tags:
      - upgrade_ambari_agent

  - name: display test message
    debug: msg="Test Message!!!"
    tags:
      - test_tag
